second workflow

diff --git a/.github/workflows/AzureAKS.yml b/.github/workflows/AzureAKS.yml
--- a/.github/workflows/AzureAKS.yml
+++ b/.github/workflows/AzureAKS.yml
@@ -30,47 +30,63 @@ jobs:
       - name: Azure Login
         run: az login --service-principal -u ${{ secrets.AZURE_SP_APPID }} -p ${{ secrets.AZURE_SP_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT_ID }}
 
-      # Paso para configurar Terraform
-      - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2.0.2
+      - name: Invocar Workflow Hijo
+        uses: actions/checkout@v2
         with:
-          terraform_version: latest
-          cli_config_credentials_token: ${{ secrets.TFC_TOKEN_ID }} # Token de Terraform Cloud
+          repository: "${{ github.repository_owner }}/poc-githubactions"
+          token: "${{ secrets.PAT }}"
+          ref: feature/aks-terraform-ghactions
+          path: child-repo
 
-      # Paso para inicializar Terraform
-      - name: Terraform Init
-        id: init
-        run: terraform init
+      - name: Repository Dispatch
+        uses: peter-evans/repository-dispatch@v3
+        with:
+          token: "${{ secrets.PAT }}"
+          repository: "${{ github.repository_owner }}/poc-githubactions"
+          event-type: repository_dispatch
+          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "job-id": "execution-terraform" }'
 
-      # Paso para validar los archivos de configuración de Terraform
-      - name: Terraform Validate
-        id: validate
-        run: terraform validate
+      # # Paso para configurar Terraform
+      # - name: Setup Terraform
+      #   uses: hashicorp/setup-terraform@v2.0.2
+      #   with:
+      #     terraform_version: latest
+      #     cli_config_credentials_token: ${{ secrets.TFC_TOKEN_ID }} # Token de Terraform Cloud
 
-      # Paso para planificar los cambios en Terraform
-      - name: Terraform Plan
-        id: plan
-        run: terraform plan
-        continue-on-error: true
+      # # Paso para inicializar Terraform
+      # - name: Terraform Init
+      #   id: init
+      #   run: terraform init
 
-      # Paso para verificar si el plan de Terraform ha fallado
-      - name: Terraform Plan Status
-        if: steps.plan.outcome == 'failure'
-        run: exit 1
+      # # Paso para validar los archivos de configuración de Terraform
+      # - name: Terraform Validate
+      #   id: validate
+      #   run: terraform validate
 
-      # Paso para aplicar los cambios en Terraform (crear o actualizar recursos)
-      - name: Terraform Apply
-        run: terraform apply -auto-approve
+      # # Paso para planificar los cambios en Terraform
+      # - name: Terraform Plan
+      #   id: plan
+      #   run: terraform plan
+      #   continue-on-error: true
 
-      # Paso para obtener las salidas (outputs) de Terraform
-      - name: Terraform Output
-        run: terraform output
+      # # Paso para verificar si el plan de Terraform ha fallado
+      # - name: Terraform Plan Status
+      #   if: steps.plan.outcome == 'failure'
+      #   run: exit 1
+
+      # # Paso para aplicar los cambios en Terraform (crear o actualizar recursos)
+      # - name: Terraform Apply
+      #   run: terraform apply -auto-approve
+
+      # # Paso para obtener las salidas (outputs) de Terraform
+      # - name: Terraform Output
+      #   run: terraform output
 
       # Paso para desplegar la aplicación en el clúster AKS
-      - name: Deploy Application
-        run: |
-          az aks get-credentials -n "cluster-bursting-jennet" -g "rg-refined-swine"
-          kubectl apply -f ./AKSApp/aks-store-quickstart.yaml
-          sleep 40
-          kubectl get service store-front
-          rm -rf ~/.kube
+      # - name: Deploy Application
+      #   run: |
+      #     az aks get-credentials -n "cluster-bursting-jennet" -g "rg-refined-swine"
+      #     kubectl apply -f ./AKSApp/aks-store-quickstart.yaml
+      #     sleep 40
+      #     kubectl get service store-front
+      #     rm -rf ~/.kube
